### ISSUE TITLE
Favoring abstract claims

### ISSUE THREAD

**Issue by msporny** [opencreds/vc-data-model#6]
We need text in the specification that notes that all ecosystem participants should favor “proof of” vs. “actual data”. Example: overAge: 21 vs. birthdate. There are benefits for issuers, holders, and inspectors; we should specify what these are.

**Comment by ottonomy** [comment]
In order to enable recipients of verifiable claims to use them in a variety of circumstances without revealing more personally identifiable information than necessary for the transaction, issuers should consider limiting the information published in a claim to a minimal set needed for the expected purposes.

For example, if retailers in a market commonly require purchasers to be older than a specific age, a trusted issuer may choose to offer a credential claiming that subjects have met that requirement ("ageOver") as opposed to offering claims of their specific birthdates. This enables individual customers to purchase items without revealing specific personally identifiable information.

**Comment by msporny** [comment]
@ottonomy Could you create a PR from your proposed text so we can do a review?
